# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('edited', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('path', models.CharField(db_index=True, max_length=255, verbose_name='Path')),
                ('method', models.CharField(max_length=6, verbose_name='Method')),
                ('ip', models.CharField(max_length=12, verbose_name='Ip')),
                ('user_agent', models.CharField(max_length=255, verbose_name='User agent')),
                ('authenticated', models.BooleanField(default=False, verbose_name='Authenticated user')),
                ('staff', models.BooleanField(default=False, verbose_name='Staff user')),
                ('superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('username', models.CharField(db_index=True, max_length=120, verbose_name='Username')),
                ('referer', models.CharField(blank=True, max_length=255, verbose_name='Referer')),
                ('view', models.CharField(blank=True, max_length=120, verbose_name='View')),
                ('module', models.CharField(blank=True, max_length=120, verbose_name='Module')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Status code')),
                ('reason_phrase', models.CharField(blank=True, max_length=120, verbose_name='Reason phrase')),
                ('request_time', models.PositiveIntegerField(verbose_name='Request time')),
                ('doc_size', models.PositiveIntegerField(verbose_name='Document size')),
                ('num_queries', models.PositiveIntegerField(verbose_name='Number of queries')),
                ('queries_time', models.PositiveIntegerField(verbose_name='Queries time')),
                ('is_pc', models.BooleanField(default=False, verbose_name='PC')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Bot')),
                ('os', models.CharField(max_length=120, verbose_name='Operating system')),
                ('os_version', models.CharField(max_length=120, verbose_name='Operating system version')),
                ('is_tablet', models.BooleanField(default=False, verbose_name='Tablet')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='Mobile')),
                ('is_touch', models.BooleanField(default=False, verbose_name='Has touch capabilities')),
                ('browser', models.CharField(max_length=255, verbose_name='Browser')),
                ('device', models.CharField(max_length=255, verbose_name='Device')),
                ('country', models.CharField(max_length=120, verbose_name='Country')),
                ('latitude', models.CharField(max_length=24, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=25, verbose_name='Longitude')),
                ('region', models.CharField(max_length=120, verbose_name='Region')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
            ],
            options={
                'verbose_name': 'Hit',
                'verbose_name_plural': 'Hits',
                'ordering': ['-created'],
            },
        ),
    ]
